cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [    
path('', views.cart_detail, name='cart_detail'),    
path('add/<int:product_id>/', views.cart_add, name='cart_add'),    
path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [    path('admin/', admin.site.urls),
path('cart/', include('cart.urls', namespace='cart')),
path('orders/', include('orders.urls', namespace='orders')),    
path('', include('shop.urls', namespace='shop')),]

if settings.DEBUG:    
	urlpatterns += static(settings.MEDIA_URL,
		document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'

urlpatterns = [    
path('create/', views.order_create, name='order_create'),]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [    path('', views.product_list, name='product_list'),    
path('<slug:category_slug>/', views.product_list,          
	name='product_list_by_category'),    
path('<int:id>/<slug:slug>/', views.product_detail,         
	name='product_detail'),]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
# Create your models here.
from django.db import models
from shop.models import Product
class Order(models.Model):    
	first_name = models.CharField(max_length=50)    
	last_name = models.CharField(max_length=50)    
	email = models.EmailField()    
	address = models.CharField(max_length=250)    
	postal_code = models.CharField(max_length=20)    
	city = models.CharField(max_length=100)    
	created = models.DateTimeField(auto_now_add=True)    
	updated = models.DateTimeField(auto_now=True)    
	paid = models.BooleanField(default=False)    
	class Meta:        
		ordering = ('-created',)    

	def __str__(self):        
		return 'Order {}'.format(self.id)    

	def get_total_cost(self):        
		return sum(item.get_cost() 
			for item in self.items.all())

class OrderItem(models.Model):    
	order = models.ForeignKey(Order,                              
		related_name='items',                              
		on_delete=models.CASCADE)    
	product = models.ForeignKey(Product,                                
		related_name='order_items',                                
		on_delete=models.CASCADE)    
	price = models.DecimalField(max_digits=10, decimal_places=2)    
	quantity = models.PositiveIntegerField(default=1)    

	def __str__(self):        
		return '{}'.format(self.id)    


	def get_cost(self):        
		return self.price * self.quantity

shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model): 
	name = models.CharField(max_length=200,   db_index=True) 
	slug = models.SlugField(max_length=200, unique=True) 

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):        
		return reverse('shop:product_list_by_category',                       
			args=[self.slug])


class Product(models.Model): 
	category = models.ForeignKey(Category, related_name='products',   
				on_delete=models.CASCADE) 
	name = models.CharField(max_length=200, db_index=True) 
	slug = models.SlugField(max_length=200, db_index=True) 
	image = models.ImageField(upload_to='products/%Y/%m/%d',   blank=True) 
	description = models.TextField(blank=True) 
	price = models.DecimalField(max_digits=10, decimal_places=2) 
	available = models.BooleanField(default=True) 
	created = models.DateTimeField(auto_now_add=True) 
	updated = models.DateTimeField(auto_now=True)

	class Meta: 
		ordering = ('name',) 
		index_together = (('id', 'slug'),) 

	def __str__(self): 
		return self.name


	def get_absolute_url(self):        
		return reverse('shop:product_detail',                       
			args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):    
	quantity = forms.TypedChoiceField(                                
				choices=PRODUCT_QUANTITY_CHOICES,                                
				coerce=int)    
	update = forms.BooleanField(required=False,                                
								initial=False,                                
								widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order
class OrderCreateForm(forms.ModelForm):    
	class Meta:        
		model = Order        
		fields = ['first_name', 'last_name', 'email', 'address','postal_code', 'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):    
	cart = Cart(request)    
	product = get_object_or_404(Product, id=product_id)    
	form = CartAddProductForm(request.POST)    
	if form.is_valid():        
		cd = form.cleaned_data        
		cart.add(product=product,                 
			quantity=cd['quantity'],                 
			update_quantity=cd['update'])    
	return redirect('cart:cart_detail')


def cart_remove(request, product_id):    
	cart = Cart(request)    
	product = get_object_or_404(Product, id=product_id)    
	cart.remove(product)    
	return redirect('cart:cart_detail')

def cart_detail(request):    
	cart = Cart(request)
	for item in cart:        
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],                          
		'update': True})  
	return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
# Create your views here.
def order_create(request):    
	cart = Cart(request)    
	if request.method == 'POST':        
		form = OrderCreateForm(request.POST)        
		if form.is_valid():            
			order = form.save()            
			for item in cart:                
				OrderItem.objects.create(order=order,                                         
				product=item['product'],                                         
				price=item['price'],                                         
				quantity=item['quantity'])            
				# clear the cart            
				cart.clear()            
			return render(request,                          
				'orders/order/created.html',                          
				{'order': order})    
	else:        
		form = OrderCreateForm()    
	return render(request,                  
		'orders/order/create.html',                  
		{'cart': cart, 'form': form})

shop/views.py
#from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
def product_list(request, category_slug=None):    
	category = None    
	categories = Category.objects.all()    
	products = Product.objects.filter(available=True)    
	if category_slug:        
		category = get_object_or_404(Category, slug=category_slug)        
		products = products.filter(category=category)    
	return render(request,                  
			'shop/product/list.html',                  
			{'category': category,                   
			'categories': categories,                   
			'products': products})


def product_detail(request, id, slug):    
	product = get_object_or_404(Product,                                
		id=id,                                
		slug=slug,                                
		available=True) 
	cart_product_form = CartAddProductForm()   
	return render(request,                  
		'shop/product/detail.html',                  
		{'product': product,
		'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}  Your shopping cart{% endblock %}
{% block content %}  
<h1>Your shopping cart</h1>  
<table class="table table-striped">    
	<thead>      
		<tr>        
			<th>Image</th>        
			<th>Product</th>        
			<th>Quantity</th>        
			<th>Remove</th>        
			<th>Unit price</th>        
			<th>Price</th>      
		</tr>    
	</thead>   
<tbody>
	{% for item in cart %}        
		{% with product=item.product %}          
		<tr>            
			<td>              
				<a href="{{ product.get_absolute_url }}">                
					<img  width="200px;" height="200px;"  src="{% if product.image %}{{ product.image.url }}                
					{% else %}{% static 'img/no_image.png' %}{% endif %}">              
				</a>            
			</td>            
			<td>{{ product.name }}</td>            
			<td>
				<form action="{% url 'cart:cart_add' product.id %}" method="post">
					{{ item.update_quantity_form.quantity }}    
					{{ item.update_quantity_form.update }}    
					<input type="submit" value="Update">    
					{% csrf_token %}  
				</form>
			</td>			
			<td>
				<a href="{% url 'cart:cart_remove' product.id %}">Remove</a>
			</td>            
			<td class="num">${{ item.price }}</td>            
			<td class="num">${{ item.total_price }}</td>          
		</tr>        
		{% endwith %}      
	{% endfor %}      
		<tr class="total">        
			<td>Total</td>        
			<td colspan="4"></td>        
			<td class="num">${{ cart.get_total_price }}</td>      
		</tr>    
	</tbody>  
</table>  
<p class="text-right">    
	<a href="{% url 'shop:product_list' %}" class="btn btn-success">Continue shopping</a>    
	<a href="{% url 'orders:order_create' %}" class="btn btn-success">  Checkout</a></p>
{% endblock %}

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% block title %}  Checkout{% endblock %}
{% block content %}  
<br><h2 >Checkout</h2> <br>
<div class="row">
<div class="col-md-6">
<div class="card bg-light text-dark" style="width: 18rem;"><br>    
	<h3>Your order</h3>    
	<ul class="list-group">      
		{% for item in cart %}        
		<li class="list-group-item ">          
			{{ item.quantity }}x {{ item.product.name }}          
			<span>${{ item.total_price }}</span>        
		</li>      
		{% endfor %}    
	</ul>    
<p>Total: ${{ cart.get_total_price }}</p>  
</div>
</div>
<div class="col-md-2">
<form action="." method="post">    
	{{ form.as_p }}    
	<p><input type="submit" class = "btn btn-success" value="Place order"></p>    
	{% csrf_token %}  
</form>
</div>
</div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% block title %}  Thank you{% endblock %}
{% block content %}  
<h1>Thank you</h1>  
<p>Your order has been successfully completed. Your order number is    <strong>{{ order.id }}</strong>.
</p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>  
	<meta charset="utf-8" />  
	<title>
	{% block title %}
	My Pet Shop
	{% endblock %}
	</title>  
	<link href="{% static 'css/base.css'%}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body style="font-style: italic;color: white; background-image: url({% static 'img/bg.jpg' %});">  
	<div class="navbar navbar-dark bg-dark" style="font-size: 30px;"> 
	<a href="/"><img src="{% static 'img/logo.jpg' %}" width="60px;" height="60px;" alt="logo">  Happy Paws Shoppy</a>  
	</div>  
		<div class="navbar navbar-light bg-light" style="color: black;">      
		{% with total_items=cart|length %}    
			{% if cart|length > 0 %}      
				<a href="{% url 'cart:cart_detail' %}">  
				<h5>Your cart:</h5>        
				{{ total_items }} item{{ total_items|pluralize }},        
				${{ cart.get_total_price }}      
				</a>    
			{% else %}      
				Your cart is empty.    
			{% endif %}  
		{% endwith %}    
		</div>  
	<div class="container"> 
	{% block content %}    
	{% endblock %}  
	</div>
</body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}  {{ product.name }}{% endblock %}
{% block content %}  
<h3>Category - <a href="{{ product.category.get_absolute_url }}" style="color: black">{{product.category }}</a></h3>
<div class="row">    
	<div class="col-md-6">
	<img src="{% if product.image %}{{ product.image.url }}{% else %}    {% static 'img/no_image.png' %}{% endif %}">    
	</div>
	<div class="col-md-6">
	<h1>{{ product.name }}</h1> 
	<p class="price">${{ product.price }}</p>
	<form action="{% url 'cart:cart_add' product.id %}" method="post">  
		{{ cart_product_form }}  
		{% csrf_token %}  
		<input type="submit" value="Add to cart">
	</form>
	{{ product.description|linebreaks }} 
</div>
</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}  
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %} 
<div class="row"> 
	<div class ="col-md-3"> 
	<h3>Categories</h3>     
	<ul class = "list-group">      
		<li class="list-group-item" {% if not category %}class="selected"{% endif %}>   <a href="{% url 'shop:product_list' %}">All</a>      
		</li>      
		{% for c in categories %}        
		<li class="list-group-item" {% if category.slug == c.slug %}class="selected" {% endif %}>          
			<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>        
		</li>      
	{% endfor %}    
</ul>  
</div>  

<div id="main" class="col-md-9">    
	<h1>{% if category %}{{ category.name }}{% else %}Animals{% endif %}</h1> 
	<div class="row">   
	{% for product in products %} 
				<div class="col-md-3">        
				<a href="{{ product.get_absolute_url }}"> <br>         
				<img class = "img-responsive" width="200px;" height="150px;" src="{% if product.image %}{{ product.image.url }}
				{% else %}
				{% static 'img/no_image.png' %}{% endif %}">        
				</a>  
				<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>        
				<br>      
				${{ product.price }}
				</div>  
	{% endfor %}  
</div>  
</div>
</div>
{% endblock %}